import { DateTime } from "luxon";
import { MessageFlags, type Interaction } from "discord.js";
import type { AppContext } from "./context.js";
import { blackjackControls } from "../ui/components.js";
import { publicErrorMessage, ValidationError } from "../utilities/errors.js";

export async function handleInteraction(interaction: Interaction, context: AppContext): Promise<void> {
 try {
  if (interaction.isButton() && interaction.customId.startsWith("daily-dilemma:vote:")) { const [, , choice, poll] = interaction.customId.split(":"); await interaction.deferReply({ flags: MessageFlags.Ephemeral }); const result = await context.dailyDilemma.submitVote(Number(poll), choice as "red" | "blue", interaction.user.id); await interaction.editReply(result === "accepted" ? "Your vote was recorded." : result === "duplicate" ? "You already voted." : "Voting is unavailable; open the Daily Dilemma link to vote."); return; }
  if (interaction.isButton() && interaction.customId.startsWith("blackjack:")) { const [, action, id] = interaction.customId.split(":"); const game = action === "hit" ? await context.blackjack.hit(interaction.guildId!, interaction.user.id, Number(id), interaction.id) : await context.blackjack.stand(interaction.guildId!, interaction.user.id, Number(id), interaction.id); await interaction.update({ content: `Blackjack hand #${game.id}: **${game.status}**`, components: [blackjackControls(game)] }); return; }
  if (!interaction.isChatInputCommand() || interaction.commandName !== "casino" || !interaction.guildId || !interaction.guild) return;
  const group = interaction.options.getSubcommandGroup(false); const sub = interaction.options.getSubcommand(); const guildId = interaction.guildId; const userId = interaction.user.id;
  if (group === "setup") { const member = await interaction.guild.members.fetch(userId); if (!member.permissions.has("Administrator")) throw new ValidationError("Only server administrators can change CasinoBot setup."); const existing = await context.prisma.guildSetting.upsert({ where: { guildId }, create: { guildId, timezone: context.config.DEFAULT_TIMEZONE }, update: {} }); if (sub === "timezone") { const timezone = interaction.options.getString("timezone", true); if (!DateTime.now().setZone(timezone).isValid) throw new ValidationError("Use a valid IANA timezone, such as America/Toronto."); await context.prisma.guildSetting.update({ where: { guildId }, data: { timezone } }); await interaction.reply({ content: `Timezone set to **${timezone}**.`, flags: MessageFlags.Ephemeral }); } else { const channel = interaction.options.getChannel("channel"); const field = sub === "dilemma-channel" ? "dilemmaChannelId" : "casinoReminderChannelId"; await context.prisma.guildSetting.update({ where: { guildId }, data: { [field]: channel?.id ?? null } }); await interaction.reply({ content: channel ? `Configured <#${channel.id}>.` : `Disabled ${sub}.`, flags: MessageFlags.Ephemeral }); } void existing; return; }
  if (group === "blackjack") { const game = sub === "play" ? await context.blackjack.start(guildId, userId, interaction.options.getInteger("wager", true), interaction.id) : await context.blackjack.activeGame(guildId, userId); await interaction.reply({ content: `Blackjack hand #${game.id}: **${game.status}**`, components: [blackjackControls(game)] }); return; }
  if (sub === "balance") { const balance = await context.casino.balance(guildId, userId); await interaction.reply({ content: `You have **${balance.toLocaleString()} chips**.`, flags: MessageFlags.Ephemeral }); return; }
  if (sub === "daily") { const r = await context.casino.claimDaily(guildId, userId); await interaction.reply({ content: `Claimed **${r.amount} chips**. Balance: **${r.balance.toLocaleString()}**.`, flags: MessageFlags.Ephemeral }); return; }
  if (sub === "notifications") { await context.casino.setReminders(guildId, userId, interaction.options.getString("setting", true) === "on"); await interaction.reply({ content: "Notification preference saved.", flags: MessageFlags.Ephemeral }); return; }
  if (sub === "transfer") { const member = interaction.options.getUser("member", true); const r = await context.casino.transfer(guildId, userId, member.id, interaction.options.getInteger("amount", true), interaction.id); await interaction.reply(`Sent **${r.amount.toLocaleString()} chips** to <@${member.id}>.`); return; }
  if (sub === "leaderboard") { const rows = await context.casino.leaderboard(guildId); await interaction.reply(`🎰 **Leaderboard**\n${rows.slice(0, 10).map((r, i) => `${i + 1}. <@${r.userId}> — **${r.balance.toLocaleString()}**`).join("\n") || "No players yet."}`); return; }
  if (sub === "history") { const rows = await context.casino.history(guildId, userId); await interaction.reply({ content: rows.map(r => `${r.game}: ${r.delta > 0 ? "+" : ""}${r.delta}`).join("\n") || "No transactions yet.", flags: MessageFlags.Ephemeral }); return; }
  if (sub === "odds") { await interaction.reply({ content: "Coin flip 2× · dice 2× (ties push) · slots up to 30× · crash targets 2×–10× · European roulette 36× straight / 2× even-money · blackjack 3:2 natural.", flags: MessageFlags.Ephemeral }); return; }
  if (sub === "stats") { const s = await context.casino.stats(guildId, userId); await interaction.reply({ content: `Balance: **${s.balance}** · games: **${s.gamesPlayed}** · wagered: **${s.totalWagered}** · returned: **${s.totalReturned}**`, flags: MessageFlags.Ephemeral }); return; }
  const wager = interaction.options.getInteger("wager", true); let result;
  if (sub === "coinflip") result = await context.casino.playCoinFlip(guildId, userId, wager, interaction.options.getString("side", true) as any, interaction.id); else if (sub === "dice") result = await context.casino.playDice(guildId, userId, wager, interaction.id); else if (sub === "slots") result = await context.casino.playSlots(guildId, userId, wager, interaction.id); else if (sub === "crash") result = await context.casino.playCrash(guildId, userId, wager, interaction.options.getInteger("target", true) as any, interaction.id); else result = await context.casino.playRoulette(guildId, userId, wager, interaction.options.getString("bet", true) as any, interaction.options.getInteger("number") ?? undefined, interaction.id);
  await interaction.reply(`${result.won ? "🎉 You won" : result.pushed ? "Push" : "The house won"}. ${result.outcome} Balance: **${result.balance.toLocaleString()}**.`);
 } catch (error) { context.logger.error({ error, interactionId: interaction.id }, "Interaction failed"); if (interaction.isRepliable()) { const content = publicErrorMessage(error); if (interaction.deferred || interaction.replied) await interaction.editReply({ content, components: [] }).catch(() => undefined); else await interaction.reply({ content, flags: MessageFlags.Ephemeral }).catch(() => undefined); } }
}
